apiVersion: skaffold/v2beta29
kind: Config

metadata:
  name: ngrok-controller

build:
  artifacts:
    - image: vasu1124/ngrok-controller
      context: .
      docker:
        dockerfile: Dev.Dockerfile
      sync:
        manual:
          - src: src/**/*
            dest: /app/

profiles:
  - name: Run Profile
    activation:
      - command: run
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Prod.Dockerfile
    deploy:
      kustomize:
        paths: 
        - "kubernetes/ngrok-controller"

  - name: Development Profile
    activation:
      - command: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dev.Dockerfile
    deploy:
      kustomize:
        paths: 
        - "kubernetes/ngrok-controller"
        - "kubernetes/httpbin"
    portForward:
    - resourceType: Deployment
      resourceName: ngrok-controller
      namespace: ngrok-controller
      port: 9229
      localPort: 9229

