apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ngrok-controller-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ngrok-controller
subjects:
- kind: ServiceAccount
  name: sa-ngrok-controller
  namespace: ngrok-controller
