apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ngrok-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/status
  - ServiceAccount
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
