apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap.yaml
- service.yaml
- deployment.yaml

# labels added to all Resources
commonLabels:
  app: ngrok-controller

# must be default for debugging with vscode
namespace: default