apiVersion: v1
kind: Service
metadata:
  name: ngrok-monitor
  namespace: ngrok-controller
  labels:
    app: ngrok-controller
spec:
  ports:
  - name: http
    port: 4040
    targetPort: 4040
    protocol: TCP
  selector:
    app: ngrok-controller
