apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- namespace.yaml
- deployment.yaml
- service-1.yaml
- service-2.yaml

# labels added to all Resources
commonLabels:
  app: httpbin

namespace: test
