apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: test
  labels:
    app: httpbin
  annotations:
    vasu1124/ngrok: http2
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
    protocol: TCP
  - name: http2
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: httpbin